// Fictional pre-authored examples at public city anchors. No company, event, lead, or observed loss is represented.
export const regions = {
  northAmerica: { names: { en:'North America', fr:'Amérique du Nord', ar:'أمريكا الشمالية', ru:'Северная Америка', zh:'北美洲', ko:'북아메리카' }, bounds:[[12,-140],[72,-50]] },
  southAmerica: { names: { en:'South America', fr:'Amérique du Sud', ar:'أمريكا الجنوبية', ru:'Южная Америка', zh:'南美洲', ko:'남아메리카' }, bounds:[[-58,-84],[14,-32]] },
  europe: { names: { en:'Europe', fr:'Europe', ar:'أوروبا', ru:'Европа', zh:'欧洲', ko:'유럽' }, bounds:[[34,-14],[72,42]] },
  africa: { names: { en:'Africa', fr:'Afrique', ar:'أفريقيا', ru:'Африка', zh:'非洲', ko:'아프리카' }, bounds:[[-36,-20],[38,55]] },
  middleEast: { names: { en:'Middle East', fr:'Moyen-Orient', ar:'الشرق الأوسط', ru:'Ближний Восток', zh:'中东', ko:'중동' }, bounds:[[12,34],[42,65]] },
  asia: { names: { en:'Asia', fr:'Asie', ar:'آسيا', ru:'Азия', zh:'亚洲', ko:'아시아' }, bounds:[[-12,28],[72,180]] },
  oceania: { names: { en:'Oceania', fr:'Océanie', ar:'أوقيانوسيا', ru:'Океания', zh:'大洋洲', ko:'오세아니아' }, bounds:[[-50,110],[2,180]] }
};

export const cities = [
  {id:'new-york',countryCode:'USA',regionId:'northAmerica',lat:40.7128,lng:-74.006,names:{en:'New York',fr:'New York',ar:'نيويورك',ru:'Нью-Йорк',zh:'纽约',ko:'뉴욕'},countries:{en:'United States',fr:'États-Unis',ar:'الولايات المتحدة',ru:'США',zh:'美国',ko:'미국'}},
  {id:'mexico-city',countryCode:'MEX',regionId:'northAmerica',lat:19.4326,lng:-99.1332,names:{en:'Mexico City',fr:'Mexico',ar:'مكسيكو سيتي',ru:'Мехико',zh:'墨西哥城',ko:'멕시코시티'},countries:{en:'Mexico',fr:'Mexique',ar:'المكسيك',ru:'Мексика',zh:'墨西哥',ko:'멕시코'}},
  {id:'sao-paulo',countryCode:'BRA',regionId:'southAmerica',lat:-23.5505,lng:-46.6333,names:{en:'São Paulo',fr:'São Paulo',ar:'ساو باولو',ru:'Сан-Паулу',zh:'圣保罗',ko:'상파울루'},countries:{en:'Brazil',fr:'Brésil',ar:'البرازيل',ru:'Бразилия',zh:'巴西',ko:'브라질'}},
  {id:'london',countryCode:'GBR',regionId:'europe',lat:51.5072,lng:-0.1276,names:{en:'London',fr:'Londres',ar:'لندن',ru:'Лондон',zh:'伦敦',ko:'런던'},countries:{en:'United Kingdom',fr:'Royaume-Uni',ar:'المملكة المتحدة',ru:'Великобритания',zh:'英国',ko:'영국'}},
  {id:'berlin',countryCode:'DEU',regionId:'europe',lat:52.52,lng:13.405,names:{en:'Berlin',fr:'Berlin',ar:'برلين',ru:'Берлин',zh:'柏林',ko:'베를린'},countries:{en:'Germany',fr:'Allemagne',ar:'ألمانيا',ru:'Германия',zh:'德国',ko:'독일'}},
  {id:'lagos',countryCode:'NGA',regionId:'africa',lat:6.5244,lng:3.3792,names:{en:'Lagos',fr:'Lagos',ar:'لاغوس',ru:'Лагос',zh:'拉各斯',ko:'라고스'},countries:{en:'Nigeria',fr:'Nigéria',ar:'نيجيريا',ru:'Нигерия',zh:'尼日利亚',ko:'나이지리아'}},
  {id:'nairobi',countryCode:'KEN',regionId:'africa',lat:-1.2921,lng:36.8219,names:{en:'Nairobi',fr:'Nairobi',ar:'نيروبي',ru:'Найроби',zh:'内罗毕',ko:'나이로비'},countries:{en:'Kenya',fr:'Kenya',ar:'كينيا',ru:'Кения',zh:'肯尼亚',ko:'케냐'}},
  {id:'mumbai',countryCode:'IND',regionId:'asia',lat:19.076,lng:72.8777,names:{en:'Mumbai',fr:'Mumbai',ar:'مومباي',ru:'Мумбаи',zh:'孟买',ko:'뭄바이'},countries:{en:'India',fr:'Inde',ar:'الهند',ru:'Индия',zh:'印度',ko:'인도'}},
  {id:'singapore',countryCode:'SGP',regionId:'asia',lat:1.3521,lng:103.8198,names:{en:'Singapore',fr:'Singapour',ar:'سنغافورة',ru:'Сингапур',zh:'新加坡',ko:'싱가포르'},countries:{en:'Singapore',fr:'Singapour',ar:'سنغافورة',ru:'Сингапур',zh:'新加坡',ko:'싱가포르'}},
  {id:'tokyo',countryCode:'JPN',regionId:'asia',lat:35.6762,lng:139.6503,names:{en:'Tokyo',fr:'Tokyo',ar:'طوكيو',ru:'Токио',zh:'东京',ko:'도쿄'},countries:{en:'Japan',fr:'Japon',ar:'اليابان',ru:'Япония',zh:'日本',ko:'일본'}},
  {id:'sydney',countryCode:'AUS',regionId:'oceania',lat:-33.8688,lng:151.2093,names:{en:'Sydney',fr:'Sydney',ar:'سيدني',ru:'Сидней',zh:'悉尼',ko:'시드니'},countries:{en:'Australia',fr:'Australie',ar:'أستراليا',ru:'Австралия',zh:'澳大利亚',ko:'호주'}},
  {id:'johannesburg',countryCode:'ZAF',regionId:'africa',lat:-26.2041,lng:28.0473,names:{en:'Johannesburg',fr:'Johannesburg',ar:'جوهانسبرغ',ru:'Йоханнесбург',zh:'约翰内斯堡',ko:'요하네스버그'},countries:{en:'South Africa',fr:'Afrique du Sud',ar:'جنوب أفريقيا',ru:'Южная Африка',zh:'南非',ko:'남아프리카공화국'}},
  {id:'dubai',countryCode:'ARE',regionId:'middleEast',lat:25.2048,lng:55.2708,names:{en:'Dubai',fr:'Dubaï',ar:'دبي',ru:'Дубай',zh:'迪拜',ko:'두바이'},countries:{en:'United Arab Emirates',fr:'Émirats arabes unis',ar:'الإمارات العربية المتحدة',ru:'ОАЭ',zh:'阿联酋',ko:'아랍에미리트'}}
];

export const sectors = {
  homeServices:{names:{en:'Home services',fr:'Services à domicile',ar:'الخدمات المنزلية',ru:'Бытовые услуги',zh:'居家服务',ko:'홈 서비스'},ticket:[120,220],prospects:[8,22],recoverable:[.03,.12]},
  fieldOperations:{names:{en:'Field operations',fr:'Opérations de terrain',ar:'العمليات الميدانية',ru:'Выездные операции',zh:'现场运营',ko:'현장 운영'},ticket:[180,360],prospects:[5,16],recoverable:[.04,.13]},
  commerce:{names:{en:'Local commerce',fr:'Commerce local',ar:'التجارة المحلية',ru:'Местная торговля',zh:'本地商业',ko:'지역 상거래'},ticket:[45,140],prospects:[12,35],recoverable:[.02,.09]},
  professionalServices:{names:{en:'Professional services',fr:'Services professionnels',ar:'الخدمات المهنية',ru:'Профессиональные услуги',zh:'专业服务',ko:'전문 서비스'},ticket:[160,420],prospects:[4,14],recoverable:[.03,.10]}
};

export const opportunityTypes = {
  missedDemand:{
    names:{en:'Missed demand',fr:'Demande manquée',ar:'طلب فائت',ru:'Упущенный спрос',zh:'未响应需求',ko:'놓친 수요'},
    problem:{en:'A fictional example where inbound requests may not receive a timely response. No business or request has been observed.',fr:'Exemple fictif de demandes entrantes qui pourraient recevoir une réponse tardive. Aucune entreprise ni demande n’a été observée.',ar:'مثال خيالي لطلبات واردة قد لا تتلقى ردًا في الوقت المناسب. لم تُرصد شركة أو طلب فعلي.',ru:'Вымышленный пример входящих запросов, на которые могут отвечать с задержкой. Реальные компании и запросы не наблюдались.',zh:'一个虚构示例：新请求可能未能及时得到回应。没有观察到任何真实企业或请求。',ko:'문의에 제때 응답하지 못할 수 있는 가상의 예입니다. 실제 업체나 문의는 관찰되지 않았습니다.'},
    why:{en:'If verified against authorized records, an unhandled request could indicate recoverable demand. Here it is only a hypothesis.',fr:'Si des dossiers autorisés le confirment, une demande non traitée pourrait être récupérable. Ici, ce n’est qu’une hypothèse.',ar:'إذا أكدت سجلات مصرح بها ذلك، فقد يشير الطلب غير المعالج إلى فرصة لاستعادة الطلب. هنا هو افتراض فقط.',ru:'Если разрешённые записи это подтвердят, необработанный запрос может указывать на спрос, который можно вернуть. Здесь это лишь гипотеза.',zh:'若经授权记录核实，未处理的请求可能意味着可挽回的需求。本示例仅为假设。',ko:'승인된 기록으로 확인될 경우 미처리 문의는 회복 가능한 수요를 뜻할 수 있습니다. 여기서는 가설일 뿐입니다.'},
    whyNow:{en:'More service journeys begin across digital and phone channels, which can make routing and response coverage worth reviewing. General context only—not a live trend or signal.',fr:'Les parcours de service commencent davantage par les canaux numériques et téléphoniques ; la répartition et la couverture des réponses peuvent donc mériter un examen. Contexte général uniquement, pas un signal observé.',ar:'تبدأ رحلات خدمة أكثر عبر القنوات الرقمية والهاتف، ما قد يجعل مراجعة التوجيه وتغطية الردود مفيدة. سياق عام فقط، وليس اتجاهًا أو إشارة مباشرة.',ru:'Все больше обращений начинается в цифровых и телефонных каналах, поэтому распределение и охват ответами стоит проверять. Это общий контекст, а не текущий тренд или сигнал.',zh:'越来越多服务流程始于数字或电话渠道，因此值得检查请求分配和响应覆盖。这只是一般背景，并非实时趋势或信号。',ko:'디지털·전화 채널에서 시작되는 서비스 여정이 늘면서 배정과 응답 범위를 검토할 필요가 있을 수 있습니다. 일반적 배경일 뿐 실시간 추세나 신호가 아닙니다.'},
    evidence:{en:'Timestamped source requests, consent and scope, assignment and response history, duplicate checks, operating hours, outcomes, and a defined denominator.',fr:'Demandes sources horodatées, consentement et périmètre, historique d’affectation et de réponse, doublons, horaires, résultats et dénominateur défini.',ar:'طلبات المصدر المؤرخة، والموافقة والنطاق، وسجل الإسناد والرد، وفحص التكرار، وساعات العمل، والنتائج، ومقام محدد.',ru:'Запросы с отметками времени, согласие и охват, история назначения и ответа, проверка дублей, часы работы, исходы и определённый знаменатель.',zh:'带时间戳的原始请求、同意与范围、分配及响应记录、重复检查、营业时间、结果和明确分母。',ko:'시간이 기록된 원본 문의, 동의와 범위, 배정·응답 이력, 중복 확인, 운영 시간, 결과 및 명확한 분모.'},
    action:{en:'Compare one permitted source record with a second signal; document scope, exceptions, and uncertainty before estimating value.',fr:'Comparer une source autorisée à un second signal ; consigner périmètre, exceptions et incertitudes avant toute estimation.',ar:'قارن سجلًا من مصدر مصرح به بإشارة ثانية؛ ووثّق النطاق والاستثناءات وعدم اليقين قبل تقدير القيمة.',ru:'Сопоставить одну разрешённую запись со вторым сигналом; зафиксировать охват, исключения и неопределённость до оценки ценности.',zh:'将一条获准来源记录与第二个信号比较；在估算价值前记录范围、例外和不确定性。',ko:'승인된 출처 기록 하나를 두 번째 신호와 비교하고 가치 추정 전에 범위·예외·불확실성을 기록합니다.'}
  },
  serviceGap:{
    names:{en:'Service gap',fr:'Lacune de service',ar:'فجوة في الخدمة',ru:'Пробел в обслуживании',zh:'服务缺口',ko:'서비스 공백'},
    problem:{en:'A fictional example where a service request may not reach an available team or capability. No service failure has been observed.',fr:'Exemple fictif où une demande pourrait ne pas atteindre une équipe ou une capacité disponible. Aucun échec réel n’a été observé.',ar:'مثال خيالي قد لا يصل فيه طلب الخدمة إلى فريق أو قدرة متاحة. لم يُرصد إخفاق فعلي.',ru:'Вымышленный пример: запрос может не попасть к доступной команде или ресурсу. Реальный сбой не наблюдался.',zh:'一个虚构示例：服务请求可能未能到达有空余能力的团队。没有观察到真实服务故障。',ko:'서비스 요청이 가용 팀이나 역량에 전달되지 않을 수 있는 가상의 예입니다. 실제 서비스 장애는 관찰되지 않았습니다.'},
    why:{en:'A verified handoff or capacity mismatch could point to service improvement or better utilization—not proof of a commercial loss.',fr:'Un transfert ou décalage de capacité confirmé pourrait orienter une amélioration ou une meilleure utilisation, sans prouver une perte commerciale.',ar:'قد يشير عدم تطابق مؤكد في الإحالة أو القدرة إلى تحسين الخدمة أو الاستخدام، لكنه لا يثبت خسارة تجارية.',ru:'Подтверждённый разрыв передачи или несоответствие мощности может подсказать улучшение сервиса, но не доказывает коммерческий убыток.',zh:'经核实的交接或能力错配可能提示服务改进或资源利用机会，但不能证明商业损失。',ko:'검증된 인계 또는 용량 불일치는 서비스 개선이나 활용도 향상을 시사할 수 있지만 상업적 손실을 증명하지는 않습니다.'},
    whyNow:{en:'Digital scheduling and distributed teams can make handoffs and capacity visibility important. General context only—not a live trend or signal.',fr:'La planification numérique et les équipes distribuées rendent la visibilité des transferts et des capacités importante. Contexte général uniquement, pas un signal observé.',ar:'قد تجعل الجدولة الرقمية والفرق الموزعة وضوح الإحالات والقدرات مهمًا. سياق عام فقط، وليس اتجاهًا أو إشارة مباشرة.',ru:'Цифровое планирование и распределённые команды повышают значение передачи задач и видимости мощностей. Это общий контекст, не наблюдаемый сигнал.',zh:'数字排班和分布式团队使交接流程与能力可见性更加重要。这只是一般背景，并非实时趋势或信号。',ko:'디지털 일정 관리와 분산 팀으로 인해 인계와 용량 가시성이 중요해질 수 있습니다. 일반적 배경일 뿐 관찰된 신호가 아닙니다.'},
    evidence:{en:'Authorized request and routing logs, stated capacity and schedule, handoff timestamps, exclusion rules, and service outcome.',fr:'Journaux autorisés des demandes et transferts, capacité et horaires déclarés, horodatages, règles d’exclusion et résultat.',ar:'سجلات الطلبات والتوجيه المصرح بها، والقدرة والجدول المعلنان، وتوقيت الإحالات، وقواعد الاستثناء، ونتيجة الخدمة.',ru:'Разрешённые журналы запросов и маршрутизации, заявленная мощность и график, время передачи, правила исключения и итог обслуживания.',zh:'获准的请求与路由日志、声明的容量和排班、交接时间、排除规则及服务结果。',ko:'승인된 요청·라우팅 기록, 명시된 용량과 일정, 인계 시간, 제외 규칙 및 서비스 결과.'},
    action:{en:'Check a documented handoff and capacity rule with an authorized owner; do not infer a failure from a map marker.',fr:'Vérifier une règle de transfert et de capacité documentée avec un responsable autorisé ; ne pas déduire un échec d’un marqueur.',ar:'تحقق مع مسؤول مصرح به من قاعدة موثقة للإحالة والقدرة؛ ولا تستنتج إخفاقًا من علامة الخريطة.',ru:'Проверить документированное правило передачи и мощности с уполномоченным владельцем; маркер на карте не доказывает сбой.',zh:'与获授权负责人核对有记录的交接和能力规则；不能从地图标记推断故障。',ko:'승인된 담당자와 기록된 인계·용량 규칙을 확인합니다. 지도 표시만으로 장애를 추론하지 않습니다.'}
  },
  followUpGap:{
    names:{en:'Follow-up gap',fr:'Lacune de suivi',ar:'فجوة في المتابعة',ru:'Пробел в последующем контакте',zh:'跟进缺口',ko:'후속 조치 공백'},
    problem:{en:'A fictional example where a quoted or requested next step may lack a recorded follow-up. No customer, quote, or delay has been observed.',fr:'Exemple fictif où une prochaine étape pourrait ne pas avoir de suivi consigné. Aucun client, devis ou retard réel n’a été observé.',ar:'مثال خيالي قد لا تُسجل فيه متابعة لخطوة تالية. لم يُرصد عميل أو عرض سعر أو تأخير فعلي.',ru:'Вымышленный пример, где следующий шаг после запроса или расчёта может остаться без записанного продолжения. Реальные клиенты и задержки не наблюдались.',zh:'一个虚构示例：报价或请求后的下一步可能没有跟进记录。没有观察到真实客户、报价或延迟。',ko:'견적 또는 문의 이후 다음 단계의 후속 기록이 없을 수 있는 가상의 예입니다. 실제 고객·견적·지연은 관찰되지 않았습니다.'},
    why:{en:'A verified follow-up gap could signal a process improvement opportunity. An inquiry or quote alone is not recognized revenue.',fr:'Une lacune de suivi confirmée pourrait signaler une amélioration du processus. Une demande ou un devis n’est pas à lui seul un revenu reconnu.',ar:'قد تشير فجوة متابعة مؤكدة إلى فرصة لتحسين العملية. الاستفسار أو عرض السعر وحده ليس إيرادًا محققًا.',ru:'Подтверждённый пробел в сопровождении может указать на улучшение процесса. Запрос или расчёт сам по себе не является признанной выручкой.',zh:'经核实的跟进缺口可能提示流程改进机会。单独的咨询或报价并不构成已确认收入。',ko:'검증된 후속 조치 공백은 프로세스 개선 기회를 시사할 수 있습니다. 문의나 견적만으로는 인식된 수익이 아닙니다.'},
    whyNow:{en:'Multi-channel journeys can leave a next step split across tools. General context only—not an observed trend or signal.',fr:'Les parcours multicanaux peuvent disperser les prochaines étapes entre plusieurs outils. Contexte général uniquement, pas un signal observé.',ar:'قد تتوزع الخطوات التالية عبر أدوات متعددة في الرحلات متعددة القنوات. سياق عام فقط، وليس اتجاهًا أو إشارة مرصودة.',ru:'При взаимодействии через разные каналы следующий шаг может оказаться в разных инструментах. Это общий контекст, не наблюдаемый сигнал.',zh:'多渠道流程可能使下一步记录分散在不同工具中。这只是一般背景，并非观测到的趋势或信号。',ko:'여러 채널을 거치면 다음 단계 기록이 여러 도구에 분산될 수 있습니다. 일반적 배경일 뿐 관찰된 추세나 신호가 아닙니다.'},
    evidence:{en:'Authorized request/quote IDs, owner and follow-up events, customer consent, expiry and exception rules, duplicates, and final outcome.',fr:'Identifiants autorisés des demandes/devis, responsable et événements de suivi, consentement, échéance et exceptions, doublons et résultat final.',ar:'معرّفات الطلبات/العروض المصرح بها، ومالك المتابعة وأحداثها، وموافقة العميل، وقواعد الانتهاء والاستثناءات، والتكرار والنتيجة النهائية.',ru:'Разрешённые ID запросов/расчётов, владелец и события сопровождения, согласие клиента, сроки и исключения, дубли и итог.',zh:'获准的请求/报价编号、负责人及跟进事件、客户同意、到期和例外规则、重复记录及最终结果。',ko:'승인된 문의·견적 ID, 담당자와 후속 이벤트, 고객 동의, 만료·예외 규칙, 중복 여부 및 최종 결과.'},
    action:{en:'Review the source record, consent, expiry, and exception policy with an authorized owner before drafting any follow-up.',fr:'Examiner la source, le consentement, l’échéance et la politique d’exception avec un responsable autorisé avant tout brouillon.',ar:'راجع المصدر والموافقة والانتهاء وسياسة الاستثناء مع مسؤول مصرح به قبل إعداد أي متابعة.',ru:'До подготовки любого последующего сообщения проверьте источник, согласие, срок и политику исключений с уполномоченным владельцем.',zh:'在拟定任何跟进内容前，与获授权负责人核对来源记录、同意、期限和例外政策。',ko:'후속 메시지 초안을 만들기 전에 승인된 담당자와 출처 기록, 동의, 만료 및 예외 정책을 검토합니다.'}
  },
  operationalWaste:{
    names:{en:'Operational waste',fr:'Gaspillage opérationnel',ar:'هدر تشغيلي',ru:'Операционные потери',zh:'运营浪费',ko:'운영 낭비'},
    problem:{en:'A fictional example where repeat work or unused capacity may be worth investigating. No waste or asset status has been observed.',fr:'Exemple fictif où les tâches répétées ou la capacité inutilisée pourraient mériter un examen. Aucun gaspillage ni actif réel n’a été observé.',ar:'مثال خيالي قد يستحق فيه العمل المتكرر أو القدرة غير المستخدمة المراجعة. لم يُرصد هدر أو أصل فعلي.',ru:'Вымышленный пример, где повторная работа или неиспользуемая мощность могут заслуживать проверки. Реальные потери не наблюдались.',zh:'一个虚构示例：重复工作或闲置能力可能值得调查。没有观察到真实浪费或资产状态。',ko:'반복 작업이나 미사용 용량을 검토할 수 있는 가상의 예입니다. 실제 낭비나 자산 상태는 관찰되지 않았습니다.'},
    why:{en:'If measured with consistent inputs, recurring rework or idle capacity may support cost-saving experiments. The demo has no measured inputs.',fr:'Mesurés avec des données cohérentes, les reprises ou capacités inutilisées pourraient justifier des tests d’économies. La démo ne dispose d’aucune mesure.',ar:'إذا قيس العمل المتكرر أو القدرة غير المستخدمة بمدخلات متسقة فقد يدعم تجارب خفض التكلفة. لا توجد قياسات في العرض.',ru:'При измерении на сопоставимых данных повторная работа или простой могут обосновать эксперимент по экономии. В демо измерений нет.',zh:'若用一致数据衡量，返工或闲置能力可能支持节约成本试验。本演示没有测量数据。',ko:'일관된 입력으로 측정된 재작업이나 유휴 용량은 비용 절감 실험에 도움이 될 수 있습니다. 데모에는 측정값이 없습니다.'},
    whyNow:{en:'Cost and capacity pressures can make operational review useful. General context only—not a live market signal or proof of waste.',fr:'Les pressions sur les coûts et les capacités peuvent rendre l’examen opérationnel utile. Contexte général uniquement, sans signal de marché observé.',ar:'قد تجعل ضغوط التكلفة والقدرة مراجعة العمليات مفيدة. سياق عام فقط، وليس إشارة سوق مباشرة أو إثباتًا للهدر.',ru:'Давление на расходы и мощности может сделать операционный анализ полезным. Это общий контекст, а не рыночный сигнал или доказательство потерь.',zh:'成本与能力压力可能使运营审查更有价值。这只是一般背景，并非实时市场信号或浪费证据。',ko:'비용과 용량 압박으로 운영 검토가 유용할 수 있습니다. 일반적 배경일 뿐 실시간 시장 신호나 낭비의 증거가 아닙니다.'},
    evidence:{en:'Comparable work orders or cost records, a defined period and denominator, approved asset/capacity data, repeat-work reason codes, and exclusions.',fr:'Ordres de travail ou coûts comparables, période et dénominateur définis, données autorisées sur les actifs/capacités, motifs de reprises et exclusions.',ar:'أوامر عمل أو سجلات تكلفة قابلة للمقارنة، وفترة ومقام محددان، وبيانات أصول/قدرات مصرح بها، وأسباب التكرار والاستثناءات.',ru:'Сопоставимые наряды или затраты, определённый период и знаменатель, разрешённые данные об активах/мощностях, причины повторных работ и исключения.',zh:'可比工单或成本记录、明确期间与分母、获准的资产/能力数据、返工原因代码及排除项。',ko:'비교 가능한 작업 지시서·비용 기록, 정의된 기간과 분모, 승인된 자산·용량 데이터, 재작업 사유 코드 및 제외 항목.'},
    action:{en:'Establish a baseline and review one traceable exception with the accountable operations owner; do not label it a loss until confirmed.',fr:'Établir une référence et examiner une exception traçable avec le responsable opérationnel ; ne pas la qualifier de perte avant confirmation.',ar:'أنشئ خط أساس وراجع استثناءً واحدًا قابلًا للتتبع مع مسؤول العمليات؛ ولا تصفه بالخسارة قبل التحقق.',ru:'Сформировать базовый уровень и проверить одно отслеживаемое исключение с ответственным руководителем; не называть его убытком до подтверждения.',zh:'先建立基线，再与负责运营的负责人审查一项可追溯例外；确认前不要称其为损失。',ko:'기준선을 만들고 운영 책임자와 추적 가능한 예외 한 건을 검토합니다. 확인 전에는 손실로 표시하지 않습니다.'}
  }
};

const sectorIds=['homeServices','fieldOperations','commerce','professionalServices'];
export const demoRecords=cities.map((city,index)=>({
  id:`ee-demo-${String(index+1).padStart(3,'0')}`,
  cityId:city.id,
  regionId:city.regionId,
  countryCode:city.countryCode,
  sector:index===12?'homeServices':sectorIds[(index*3+1)%sectorIds.length],
  type:Object.keys(opportunityTypes)[index%4],
  // Deterministic fixture inputs used for demo sorting only; not measured signal strength or confidence.
  demandIndex:[76,58,83,65,72,91,61,79,69,88,54,74,71][index],
  urgency:[68,52,75,61,57,84,49,72,63,81,46,66,62][index],
  scopeIndex:[64,55,78,59,71,82,53,74,62,86,48,69,67][index]
}));

export const verificationStatus='unverified';
