export const hudTranslations={
  en:{dockRadar:'Radar',dockAI:'AI',dockAutomation:'n8n',dockRevenue:'Revenue',dockSettings:'Settings',dockFocus:'Focus',dockFocusExit:'Exit focus',dockSafety:'Safety',hudClose:'Close',hudSynthetic:'DEMO / SYNTHETIC',hudNoConnection:'NOT CONNECTED',hudAIIntro:'No AI model or business-data source is connected. This panel describes a future review aid only.',hudAIPrinciples:'Signal ≠ proof · confidence is not assessed · human review remains required.',hudAutomationIntro:'n8n is not connected. This is a local, human-gated workflow preview only.',hudAutomationSteps:'DEMO ROUTE',hudRevenueIntro:'Illustrative synthetic scenario only—not actual lost, booked, or recovered revenue.',hudScenarioLabel:'Illustrative scenario range',hudRevenueFoot:'Assumptions are not verified. No ROI or recovery claim is made.',hudSettingsIntro:'Local display controls only. They do not connect an account, data source, or external service.',hudPerformanceMode:'Globe quality',hudAuto:'AUTO',hudPerformance:'PERFORMANCE',hudQuality:'QUALITY',hudCurrentMode:'Rendering mode',hudCurrentFps:'Measured FPS',hudSafetyIntro:'Manus Safety · human control stays in the loop.',hudSafetyRules:'No contacts, CRM writes, payments, connected business data, or hidden external actions.',hudParticipation:'Participation · local demo',hudFindOpportunity:'Find an opportunity',hudOfferSkill:'Offer a skill',hudOfferService:'Offer a service',hudParticipationNote:'Choose an example only. No personal details are collected and nothing is sent.',hudLocalOnly:'Local demo only · nothing submitted or shared.',hudStatusSelected:'Local example selected',globeStatusRecoveryFailed:'Globe recovery failed · 2D map active',hudStageDetect:'DETECT',hudStageVerify:'VERIFY',hudStageReview:'HUMAN REVIEW',hudStageApprove:'APPROVE',hudStageDisabled:'NOT CONNECTED'},
  fr:{dockRadar:'Radar',dockAI:'IA',dockAutomation:'n8n',dockRevenue:'Revenus',dockSettings:'Réglages',dockFocus:'Focus',dockFocusExit:'Quitter le focus',dockSafety:'Sécurité',hudClose:'Fermer',hudSynthetic:'DÉMO / SYNTHÉTIQUE',hudNoConnection:'NON CONNECTÉ',hudAIIntro:'Aucun modèle d’IA ni source de données métier n’est connecté. Ce panneau décrit uniquement une aide future à la vérification.',hudAIPrinciples:'Signal ≠ preuve · confiance non évaluée · vérification humaine requise.',hudAutomationIntro:'n8n n’est pas connecté. Ceci est uniquement un aperçu local soumis à validation humaine.',hudAutomationSteps:'PARCOURS DÉMO',hudRevenueIntro:'Scénario synthétique illustratif uniquement — pas un revenu perdu, comptabilisé ou récupéré.',hudScenarioLabel:'Fourchette illustrative du scénario',hudRevenueFoot:'Hypothèses non vérifiées. Aucune revendication de ROI ou de récupération.',hudSettingsIntro:'Commandes d’affichage locales uniquement. Aucun compte, source de données ou service externe n’est connecté.',hudPerformanceMode:'Qualité du globe',hudAuto:'AUTO',hudPerformance:'PERFORMANCE',hudQuality:'QUALITÉ',hudCurrentMode:'Mode de rendu',hudCurrentFps:'IPS mesurées',hudSafetyIntro:'Manus Safety · le contrôle humain reste essentiel.',hudSafetyRules:'Aucun contact, écriture CRM, paiement, donnée métier connectée ou action externe cachée.',hudParticipation:'Participation · démo locale',hudFindOpportunity:'Trouver une opportunité',hudOfferSkill:'Proposer une compétence',hudOfferService:'Proposer un service',hudParticipationNote:'Choisissez uniquement un exemple. Aucune donnée personnelle n’est collectée et rien n’est envoyé.',hudLocalOnly:'Démo locale uniquement · rien n’est transmis.',hudStatusSelected:'Exemple local sélectionné',globeStatusRecoveryFailed:'Récupération du globe impossible · carte 2D active',hudStageDetect:'DÉTECTER',hudStageVerify:'VÉRIFIER',hudStageReview:'REVUE HUMAINE',hudStageApprove:'APPROUVER',hudStageDisabled:'NON CONNECTÉ'},
  ar:{dockRadar:'الرادار',dockAI:'الذكاء الاصطناعي',dockAutomation:'أتمتة n8n',dockRevenue:'الإيرادات',dockSettings:'الإعدادات',dockFocus:'التركيز',dockFocusExit:'إنهاء التركيز',dockSafety:'الأمان',hudClose:'إغلاق',hudSynthetic:'تجريبي / اصطناعي',hudNoConnection:'غير متصل',hudAIIntro:'لا يوجد نموذج ذكاء اصطناعي أو مصدر بيانات أعمال متصل. يوضح هذا اللوح تصورًا مستقبليًا لمساعدة المراجعة فقط.',hudAIPrinciples:'الإشارة لا تساوي الدليل · الثقة غير مقاسة · المراجعة البشرية مطلوبة.',hudAutomationIntro:'n8n غير متصل. هذا عرض محلي لسير عمل مستقبلي يخضع لموافقة بشرية فقط.',hudAutomationSteps:'مسار تجريبي',hudRevenueIntro:'سيناريو اصطناعي توضيحي فقط، وليس إيرادًا مفقودًا أو مسجلًا أو مستعادًا فعليًا.',hudScenarioLabel:'نطاق السيناريو التوضيحي',hudRevenueFoot:'الافتراضات غير متحقق منها. لا يوجد ادعاء بعائد استثمار أو استعادة إيرادات.',hudSettingsIntro:'عناصر تحكم محلية للعرض فقط؛ لا تتصل بحساب أو مصدر بيانات أو خدمة خارجية.',hudPerformanceMode:'جودة الكرة الأرضية',hudAuto:'تلقائي',hudPerformance:'أداء',hudQuality:'جودة',hudCurrentMode:'وضع العرض',hudCurrentFps:'الإطارات المقاسة/ث',hudSafetyIntro:'أمان Manus · يبقى الإنسان صاحب القرار.',hudSafetyRules:'لا اتصالات أو كتابة في CRM أو مدفوعات أو بيانات أعمال متصلة أو إجراءات خارجية خفية.',hudParticipation:'المشاركة · عرض محلي',hudFindOpportunity:'اعثر على فرصة',hudOfferSkill:'اعرض مهارة',hudOfferService:'اعرض خدمة',hudParticipationNote:'اختر مثالًا فقط. لا تُجمع بيانات شخصية ولا يُرسل أي شيء.',hudLocalOnly:'عرض محلي فقط · لم يُرسل أو يُشارك شيء.',hudStatusSelected:'اختير مثال محلي',globeStatusRecoveryFailed:'تعذر استعادة الكرة · الخريطة الثنائية الأبعاد نشطة',hudStageDetect:'رصد',hudStageVerify:'تحقق',hudStageReview:'مراجعة بشرية',hudStageApprove:'موافقة',hudStageDisabled:'غير متصل'},
  ru:{dockRadar:'Радар',dockAI:'ИИ',dockAutomation:'n8n',dockRevenue:'Доход',dockSettings:'Настройки',dockFocus:'Фокус',dockFocusExit:'Выйти из фокуса',dockSafety:'Безопасность',hudClose:'Закрыть',hudSynthetic:'ДЕМО / СИНТЕТИКА',hudNoConnection:'НЕ ПОДКЛЮЧЕНО',hudAIIntro:'Модель ИИ и источник бизнес-данных не подключены. Панель описывает только возможную будущую помощь при проверке.',hudAIPrinciples:'Сигнал ≠ доказательство · достоверность не оценена · нужна проверка человеком.',hudAutomationIntro:'n8n не подключён. Это только локальный пример будущего процесса с одобрением человеком.',hudAutomationSteps:'МАРШРУТ ДЕМО',hudRevenueIntro:'Только иллюстративный синтетический сценарий — не фактически потерянный, учтённый или возвращённый доход.',hudScenarioLabel:'Иллюстративный диапазон сценария',hudRevenueFoot:'Допущения не проверены. Заявлений о ROI или возврате нет.',hudSettingsIntro:'Только локальные настройки отображения. Аккаунты, источники данных и внешние службы не подключаются.',hudPerformanceMode:'Качество глобуса',hudAuto:'АВТО',hudPerformance:'ПРОИЗВОДИТЕЛЬНОСТЬ',hudQuality:'КАЧЕСТВО',hudCurrentMode:'Режим рендеринга',hudCurrentFps:'Измерено FPS',hudSafetyIntro:'Manus Safety · решение остаётся за человеком.',hudSafetyRules:'Нет контактов, записей в CRM, платежей, подключённых бизнес-данных или скрытых внешних действий.',hudParticipation:'Участие · локальное демо',hudFindOpportunity:'Найти возможность',hudOfferSkill:'Предложить навык',hudOfferService:'Предложить услугу',hudParticipationNote:'Выберите только пример. Личные данные не собираются, ничего не отправляется.',hudLocalOnly:'Только локальное демо · ничего не отправлено.',hudStatusSelected:'Локальный пример выбран',globeStatusRecoveryFailed:'Не удалось восстановить глобус · активна 2D-карта',hudStageDetect:'НАЙТИ',hudStageVerify:'ПРОВЕРИТЬ',hudStageReview:'ПРОВЕРКА ЧЕЛОВЕКОМ',hudStageApprove:'ОДОБРИТЬ',hudStageDisabled:'НЕ ПОДКЛЮЧЕНО'},
  zh:{dockRadar:'雷达',dockAI:'AI',dockAutomation:'n8n',dockRevenue:'收入',dockSettings:'设置',dockFocus:'专注',dockFocusExit:'退出专注',dockSafety:'安全',hudClose:'关闭',hudSynthetic:'演示 / 合成',hudNoConnection:'未连接',hudAIIntro:'未连接 AI 模型或业务数据源。本面板仅说明未来可能的辅助审核方式。',hudAIPrinciples:'信号 ≠ 证据 · 未评估可信度 · 仍需人工审核。',hudAutomationIntro:'n8n 未连接。本地仅展示未来需人工批准的工作流。',hudAutomationSteps:'演示流程',hudRevenueIntro:'仅为合成示例，不代表实际损失、入账收入或已追回收入。',hudScenarioLabel:'示意情景范围',hudRevenueFoot:'假设未经核实，不作投资回报或收入追回声明。',hudSettingsIntro:'仅控制本地显示，不连接账户、数据源或外部服务。',hudPerformanceMode:'地球画质',hudAuto:'自动',hudPerformance:'性能',hudQuality:'画质',hudCurrentMode:'渲染模式',hudCurrentFps:'测得帧率',hudSafetyIntro:'Manus Safety · 保留人工控制。',hudSafetyRules:'无外部联系、CRM 写入、付款、业务数据连接或隐藏外部操作。',hudParticipation:'参与 · 本地演示',hudFindOpportunity:'查找机会',hudOfferSkill:'提供技能',hudOfferService:'提供服务',hudParticipationNote:'仅选择示例。不收集个人信息，也不会发送任何内容。',hudLocalOnly:'仅本地演示 · 未提交或分享。',hudStatusSelected:'已选择本地示例',globeStatusRecoveryFailed:'地球恢复失败 · 已启用 2D 地图',hudStageDetect:'发现',hudStageVerify:'核验',hudStageReview:'人工审核',hudStageApprove:'批准',hudStageDisabled:'未连接'},
  ko:{dockRadar:'레이더',dockAI:'AI',dockAutomation:'n8n',dockRevenue:'수익',dockSettings:'설정',dockFocus:'집중',dockFocusExit:'집중 모드 종료',dockSafety:'안전',hudClose:'닫기',hudSynthetic:'데모 / 합성',hudNoConnection:'연결되지 않음',hudAIIntro:'AI 모델이나 비즈니스 데이터 소스가 연결되지 않았습니다. 이 패널은 향후 검토 지원 개념만 설명합니다.',hudAIPrinciples:'신호 ≠ 증거 · 신뢰도 미평가 · 사람의 검토 필요.',hudAutomationIntro:'n8n은 연결되지 않았습니다. 사람의 승인을 전제로 한 향후 워크플로의 로컬 미리보기입니다.',hudAutomationSteps:'데모 경로',hudRevenueIntro:'합성 예시일 뿐 실제 손실·기록·회수 수익이 아닙니다.',hudScenarioLabel:'예시 시나리오 범위',hudRevenueFoot:'가정은 검증되지 않았으며 ROI나 수익 회수를 주장하지 않습니다.',hudSettingsIntro:'로컬 화면 설정만 변경합니다. 계정·데이터 소스·외부 서비스는 연결하지 않습니다.',hudPerformanceMode:'지구본 품질',hudAuto:'자동',hudPerformance:'성능',hudQuality:'화질',hudCurrentMode:'렌더링 모드',hudCurrentFps:'측정 FPS',hudSafetyIntro:'Manus Safety · 사람의 통제 유지.',hudSafetyRules:'연락, CRM 기록, 결제, 연결된 비즈니스 데이터 또는 숨겨진 외부 작업이 없습니다.',hudParticipation:'참여 · 로컬 데모',hudFindOpportunity:'기회 찾기',hudOfferSkill:'기술 제공',hudOfferService:'서비스 제공',hudParticipationNote:'예시만 선택합니다. 개인정보를 수집하지 않으며 아무것도 전송하지 않습니다.',hudLocalOnly:'로컬 데모만 · 제출 또는 공유되지 않았습니다.',hudStatusSelected:'로컬 예시 선택됨',globeStatusRecoveryFailed:'지구본 복구 실패 · 2D 지도가 활성화됨',hudStageDetect:'감지',hudStageVerify:'검증',hudStageReview:'사람 검토',hudStageApprove:'승인',hudStageDisabled:'연결되지 않음'}
};


export const hudExtraTranslations={
  en:{hudRevenueTitle:'Revenue Recovery',hudCouncilStatus:'Council status',hudReasoningState:'Reasoning state: hypothesis · not verified',hudEvidenceLabels:'Evidence labels',hudLanguage:'Language',hudMapControls:'Map controls',hudWhatBrings:'WHAT BRINGS YOU HERE?',hudFindClient:'Find a client',hudFindJob:'Find a job',hudFindPartner:'Find a partner',hudExplore:'Explore',hudNetworkVision:'Supply ↔ demand · skills ↔ needs · people ↔ solutions · future concept only.'},
  fr:{hudRevenueTitle:'Récupération des revenus',hudCouncilStatus:'État du conseil',hudReasoningState:'État du raisonnement : hypothèse · non vérifiée',hudEvidenceLabels:'Libellés des preuves',hudLanguage:'Langue',hudMapControls:'Commandes cartographiques',hudWhatBrings:'QU’EST-CE QUI VOUS AMÈNE ?',hudFindClient:'Trouver un client',hudFindJob:'Trouver un emploi',hudFindPartner:'Trouver un partenaire',hudExplore:'Explorer',hudNetworkVision:'Offre ↔ demande · compétences ↔ besoins · personnes ↔ solutions · concept futur uniquement.'},
  ar:{hudRevenueTitle:'استعادة الإيرادات',hudCouncilStatus:'حالة المجلس',hudReasoningState:'حالة الاستدلال: فرضية · غير متحقق منها',hudEvidenceLabels:'تسميات الأدلة',hudLanguage:'اللغة',hudMapControls:'عناصر تحكم الخريطة',hudWhatBrings:'ما الذي أتى بك إلى هنا؟',hudFindClient:'اعثر على عميل',hudFindJob:'اعثر على وظيفة',hudFindPartner:'اعثر على شريك',hudExplore:'استكشف',hudNetworkVision:'العرض ↔ الطلب · المهارات ↔ الاحتياجات · الأشخاص ↔ الحلول · تصور مستقبلي فقط.'},
  ru:{hudRevenueTitle:'Возврат дохода',hudCouncilStatus:'Статус совета',hudReasoningState:'Состояние рассуждения: гипотеза · не проверена',hudEvidenceLabels:'Метки доказательств',hudLanguage:'Язык',hudMapControls:'Управление картой',hudWhatBrings:'ЧТО ВАС ПРИВЕЛО?',hudFindClient:'Найти клиента',hudFindJob:'Найти работу',hudFindPartner:'Найти партнёра',hudExplore:'Исследовать',hudNetworkVision:'Предложение ↔ спрос · навыки ↔ потребности · люди ↔ решения · только будущая концепция.'},
  zh:{hudRevenueTitle:'收入追回',hudCouncilStatus:'评审状态',hudReasoningState:'推理状态：假设 · 未核实',hudEvidenceLabels:'证据标签',hudLanguage:'语言',hudMapControls:'地图控制',hudWhatBrings:'您为何来到这里？',hudFindClient:'寻找客户',hudFindJob:'寻找工作',hudFindPartner:'寻找伙伴',hudExplore:'探索',hudNetworkVision:'供给 ↔ 需求 · 技能 ↔ 需要 · 人 ↔ 方案 · 仅为未来概念。'},
  ko:{hudRevenueTitle:'수익 회복',hudCouncilStatus:'검토 상태',hudReasoningState:'추론 상태: 가설 · 미검증',hudEvidenceLabels:'증거 라벨',hudLanguage:'언어',hudMapControls:'지도 제어',hudWhatBrings:'무엇을 찾고 계신가요?',hudFindClient:'고객 찾기',hudFindJob:'일자리 찾기',hudFindPartner:'파트너 찾기',hudExplore:'탐색',hudNetworkVision:'공급 ↔ 수요 · 기술 ↔ 필요 · 사람 ↔ 해결책 · 미래 개념 전용.'}
};
for(const code of Object.keys(hudExtraTranslations))Object.assign(hudTranslations[code],hudExtraTranslations[code]);

Object.assign(hudTranslations.en,{hudControlsAria:'Command controls'});
Object.assign(hudTranslations.fr,{hudControlsAria:'Commandes'});
Object.assign(hudTranslations.ar,{hudControlsAria:'عناصر التحكم'});
Object.assign(hudTranslations.ru,{hudControlsAria:'Элементы управления'});
Object.assign(hudTranslations.zh,{hudControlsAria:'控制工具'});
Object.assign(hudTranslations.ko,{hudControlsAria:'명령 도구'});

const globeFallbackCopy={
 en:{globeFallbackNoWebgl:'3D Globe unavailable — showing 2D map (WebGL 2 required).',globeFallbackRecovery:'3D Globe recovery failed — showing 2D map.',globeFallbackRender:'3D Globe render failed after a controlled retry — showing 2D map.',globeFallbackAssets:'Local globe geography could not be loaded — showing 2D map.'},
 fr:{globeFallbackNoWebgl:'Globe 3D indisponible — affichage de la carte 2D (WebGL 2 requis).',globeFallbackRecovery:'Échec de la récupération du globe 3D — affichage de la carte 2D.',globeFallbackRender:'Échec du rendu du globe 3D après une nouvelle tentative — affichage de la carte 2D.',globeFallbackAssets:'Géographie locale du globe indisponible — affichage de la carte 2D.'},
 ar:{globeFallbackNoWebgl:'الكرة ثلاثية الأبعاد غير متاحة — تُعرض الخريطة ثنائية الأبعاد (يتطلب العرض WebGL 2).',globeFallbackRecovery:'فشل استرداد الكرة ثلاثية الأبعاد — تُعرض الخريطة ثنائية الأبعاد.',globeFallbackRender:'فشل رسم الكرة بعد محاولة استرداد مضبوطة — تُعرض الخريطة ثنائية الأبعاد.',globeFallbackAssets:'تعذر تحميل بيانات جغرافيا الكرة المحلية — تُعرض الخريطة ثنائية الأبعاد.'},
 ru:{globeFallbackNoWebgl:'3D-глобус недоступен — показана 2D-карта (требуется WebGL 2).',globeFallbackRecovery:'Не удалось восстановить 3D-глобус — показана 2D-карта.',globeFallbackRender:'Ошибка отрисовки глобуса после контролируемого повтора — показана 2D-карта.',globeFallbackAssets:'Не удалось загрузить локальную географию глобуса — показана 2D-карта.'},
 zh:{globeFallbackNoWebgl:'3D 地球不可用 — 正在显示 2D 地图（需要 WebGL 2）。',globeFallbackRecovery:'3D 地球恢复失败 — 正在显示 2D 地图。',globeFallbackRender:'受控重试后 3D 地球仍无法渲染 — 正在显示 2D 地图。',globeFallbackAssets:'无法加载本地地球地理数据 — 正在显示 2D 地图。'},
 ko:{globeFallbackNoWebgl:'3D 지구본을 사용할 수 없습니다 — 2D 지도를 표시합니다(WebGL 2 필요).',globeFallbackRecovery:'3D 지구본 복구 실패 — 2D 지도를 표시합니다.',globeFallbackRender:'제어된 재시도 후에도 지구본 렌더링 실패 — 2D 지도를 표시합니다.',globeFallbackAssets:'로컬 지구본 지리 데이터를 불러오지 못했습니다 — 2D 지도를 표시합니다.'}
};
for(const code of Object.keys(globeFallbackCopy))Object.assign(hudTranslations[code],globeFallbackCopy[code]);

Object.assign(hudTranslations.ar,{dockAI:'ذكاء',dockFocusExit:'خروج'});
Object.assign(hudTranslations.fr,{dockFocusExit:'Quitter focus'});
Object.assign(hudTranslations.ru,{dockFocusExit:'Выход'});

Object.assign(hudTranslations.en,{globeStatusAssetDegraded:'Local country outlines unavailable · using the procedural globe texture.'});
Object.assign(hudTranslations.fr,{globeStatusAssetDegraded:'Contours locaux indisponibles · texture du globe procédurale utilisée.'});
Object.assign(hudTranslations.ar,{globeStatusAssetDegraded:'حدود الدول المحلية غير متاحة · يُستخدم نسيج الكرة الإجرائي.'});
Object.assign(hudTranslations.ru,{globeStatusAssetDegraded:'Локальные границы недоступны · используется процедурная текстура глобуса.'});
Object.assign(hudTranslations.zh,{globeStatusAssetDegraded:'本地国界不可用 · 正在使用程序生成的地球纹理。'});
Object.assign(hudTranslations.ko,{globeStatusAssetDegraded:'로컬 국가 경계 없음 · 절차적 지구본 텍스처를 사용합니다.'});

Object.assign(hudTranslations.en,{hudMapView:'Geographic scope'});
Object.assign(hudTranslations.fr,{hudMapView:'Portée géographique'});
Object.assign(hudTranslations.ar,{hudMapView:'النطاق الجغرافي'});
Object.assign(hudTranslations.ru,{hudMapView:'Географический охват'});
Object.assign(hudTranslations.zh,{hudMapView:'地理范围'});
Object.assign(hudTranslations.ko,{hudMapView:'지리 범위'});

Object.assign(hudTranslations.en,{globeSetupError:'The 3D globe could not initialize after one controlled retry. The local 2D map remains selected.',globeStatusInitError:'Globe setup failed · local 2D map remains available'});
Object.assign(hudTranslations.fr,{globeSetupError:'Le globe 3D n’a pas pu démarrer après une nouvelle tentative contrôlée. La carte 2D locale reste sélectionnée.',globeStatusInitError:'Échec du démarrage du globe · carte 2D locale disponible'});
Object.assign(hudTranslations.ar,{globeSetupError:'تعذر بدء الكرة ثلاثية الأبعاد بعد محاولة مضبوطة واحدة. تظل الخريطة المحلية ثنائية الأبعاد محددة.',globeStatusInitError:'تعذر بدء الكرة · الخريطة المحلية ثنائية الأبعاد متاحة'});
Object.assign(hudTranslations.ru,{globeSetupError:'Не удалось запустить 3D-глобус после одной контролируемой повторной попытки. Локальная 2D-карта остаётся выбранной.',globeStatusInitError:'Не удалось запустить глобус · локальная 2D-карта доступна'});
Object.assign(hudTranslations.zh,{globeSetupError:'经过一次受控重试后，3D 地球仍无法启动。本地 2D 地图保持选中。',globeStatusInitError:'地球启动失败 · 本地 2D 地图仍可用'});
Object.assign(hudTranslations.ko,{globeSetupError:'제어된 1회 재시도 후에도 3D 지구본을 시작할 수 없습니다. 로컬 2D 지도가 선택된 상태로 유지됩니다.',globeStatusInitError:'지구본 초기화 실패 · 로컬 2D 지도 사용 가능'});
