export const phase5Translations={
  en:{
    subtitle:'HOME-SERVICE REVENUE RECOVERY CONCEPT · DEMO ONLY',radarTitle:'Revenue Recovery Radar',radarSub:'Synthetic workflow concept only · no live LSA or customer data, AI analysis, verified loss, or recovered-revenue claims.',mapTitle:'Revenue Recovery Radar',mapSub:'Public world geography · fictional city anchors, not business locations',
    globeView:'3D Globe',map2dView:'2D Map',visualModeAria:'Choose 3D globe or 2D map',globeAria:'Interactive 3D globe with fictional city anchors. Use arrow keys to rotate and plus or minus to zoom.',globeControlsAria:'3D globe controls',globeInstructions:'Drag to rotate · wheel or pinch to zoom · select a marker to inspect its synthetic hypothesis. Scroll outside the globe.',globeStatusReady:'Local 3D globe · all opportunities synthetic',globeStatusNoWebgl:'WebGL unavailable · 2D map active',globeStatusSlow:'Low rendering performance · restored the 2D map',globeStatusReduced:'Reduced visual effects for performance',globePause:'Pause rotation',globeResume:'Resume rotation',globeZoomIn:'Zoom in',globeZoomOut:'Zoom out',
    lifecycleAria:'Illustrative revenue-recovery lifecycle; no stage is verified or executed',lifecycleTitle:'RECOVERY LIFECYCLE · ILLUSTRATIVE ONLY',lifeSignal:'SIGNAL',lifeVerify:'VERIFY',lifeAnalyze:'ANALYZE',lifeRank:'RANK',lifeDecide:'DECIDE',lifeExecute:'EXECUTE',lifeDemo:'DEMO',lifeHypothesis:'HYPOTHESIS',lifePending:'PENDING',lifeDisabled:'DISABLED',
    dossierSignalLocation:'SIGNAL & LOCATION',revenueLeakagePotential:'Potential revenue leakage',hypotheticalRecoveryWorkflow:'HYPOTHETICAL RECOVERY WORKFLOW',hypotheticalRecoveryText:'Concept only: an authorized future workflow might flag an unreturned qualified inquiry, route it for verification, and prepare an internal draft for human approval. Nothing is connected, sent, or executed here.',blueprintDetect:'Detect a potential missed inquiry; verify against authorized records.',blueprintRecover:'Prepare a recovery draft for a human decision; send nothing.',blueprintMeasure:'Measure only a confirmed booking and its later outcome.',
    claimStates:'CLAIM STATES',claimLegendTitle:'Evidence-state vocabulary',claimLegendHint:'These labels describe possible future claim states, not evidence in this demo. Current fixtures are HYPOTHESIS or UNVERIFIED.',claimFact:'FACT',claimVerified:'VERIFIED',claimLikely:'LIKELY',claimHypothesis:'HYPOTHESIS',claimUnverified:'UNVERIFIED',claimConflicting:'CONFLICTING'
  },
  fr:{
    subtitle:'CONCEPT DE RÉCUPÉRATION DE REVENUS · DÉMO UNIQUEMENT',radarTitle:'Radar de récupération de revenus',radarSub:'Concept de workflow synthétique uniquement · aucune donnée LSA ou client en direct, analyse IA, perte vérifiée ou récupération de revenus revendiquée.',mapTitle:'Radar de récupération de revenus',mapSub:'Géographie publique · repères urbains fictifs, pas des adresses d’entreprises',
    globeView:'Globe 3D',map2dView:'Carte 2D',visualModeAria:'Choisir le globe 3D ou la carte 2D',globeAria:'Globe 3D interactif avec repères urbains fictifs. Utilisez les flèches pour le faire pivoter et plus ou moins pour zoomer.',globeControlsAria:'Commandes du globe 3D',globeInstructions:'Faites glisser pour pivoter · molette ou pincement pour zoomer · sélectionnez un repère pour voir son hypothèse synthétique. Faites défiler hors du globe.',globeStatusReady:'Globe 3D local · toutes les opportunités sont synthétiques',globeStatusNoWebgl:'WebGL indisponible · carte 2D active',globeStatusSlow:'Rendu trop lent · retour à la carte 2D',globeStatusReduced:'Effets visuels réduits pour préserver les performances',globePause:'Suspendre la rotation',globeResume:'Reprendre la rotation',globeZoomIn:'Zoom avant',globeZoomOut:'Zoom arrière',
    lifecycleAria:'Cycle illustratif de récupération de revenus ; aucune étape n’est vérifiée ou exécutée',lifecycleTitle:'CYCLE DE RÉCUPÉRATION · ILLUSTRATIF',lifeSignal:'SIGNAL',lifeVerify:'VÉRIFIER',lifeAnalyze:'ANALYSER',lifeRank:'CLASSER',lifeDecide:'DÉCIDER',lifeExecute:'EXÉCUTER',lifeDemo:'DÉMO',lifeHypothesis:'HYPOTHÈSE',lifePending:'EN ATTENTE',lifeDisabled:'DÉSACTIVÉ',
    dossierSignalLocation:'SIGNAL ET EMPLACEMENT',revenueLeakagePotential:'Fuite de revenus potentielle',hypotheticalRecoveryWorkflow:'WORKFLOW DE RÉCUPÉRATION HYPOTHÉTIQUE',hypotheticalRecoveryText:'Concept uniquement : un futur workflow autorisé pourrait signaler une demande qualifiée restée sans réponse, la soumettre à vérification et préparer un brouillon interne pour approbation humaine. Rien n’est connecté, envoyé ou exécuté ici.',blueprintDetect:'Détecter une demande potentiellement manquée et vérifier les données autorisées.',blueprintRecover:'Préparer un brouillon de récupération soumis à une décision humaine ; aucun envoi.',blueprintMeasure:'Mesurer uniquement une réservation confirmée et son résultat ultérieur.',
    claimStates:'ÉTATS DES AFFIRMATIONS',claimLegendTitle:'Vocabulaire des états de preuve',claimLegendHint:'Ces libellés décrivent des états possibles pour de futures affirmations, pas des preuves de cette démo. Les exemples actuels sont des HYPOTHÈSES ou NON VÉRIFIÉS.',claimFact:'FAIT',claimVerified:'VÉRIFIÉ',claimLikely:'PROBABLE',claimHypothesis:'HYPOTHÈSE',claimUnverified:'NON VÉRIFIÉ',claimConflicting:'CONTRADICTOIRE'
  },
  ar:{
    subtitle:'مفهوم استعادة إيرادات خدمات المنازل · عرض تجريبي فقط',radarTitle:'رادار استعادة الإيرادات',radarSub:'تصور اصطناعي لسير العمل فقط · لا توجد بيانات LSA أو عملاء مباشرة، أو تحليل ذكاء اصطناعي، أو خسائر متحقق منها، أو إيرادات مستعادة مُثبتة.',mapTitle:'رادار استعادة الإيرادات',mapSub:'جغرافيا عامة حقيقية · علامات مدن خيالية وليست مواقع شركات',
    globeView:'كرة ثلاثية الأبعاد',map2dView:'خريطة ثنائية الأبعاد',visualModeAria:'اختيار الكرة ثلاثية الأبعاد أو الخريطة ثنائية الأبعاد',globeAria:'كرة أرضية تفاعلية ثلاثية الأبعاد بعلامات مدن خيالية. استخدم الأسهم للدوران وعلامتي الجمع والطرح للتكبير والتصغير.',globeControlsAria:'عناصر التحكم بالكرة الأرضية',globeInstructions:'اسحب للتدوير · استخدم العجلة أو ضم إصبعين للتكبير · اختر علامة لفحص فرضيتها الاصطناعية. مرّر الصفحة خارج الكرة.',globeStatusReady:'كرة ثلاثية الأبعاد محلية · جميع الفرص اصطناعية',globeStatusNoWebgl:'WebGL غير متاح · الخريطة الثنائية الأبعاد نشطة',globeStatusSlow:'أداء العرض منخفض · تمت العودة إلى الخريطة الثنائية الأبعاد',globeStatusReduced:'تم تقليل المؤثرات لتحسين الأداء',globePause:'إيقاف الدوران مؤقتًا',globeResume:'استئناف الدوران',globeZoomIn:'تكبير',globeZoomOut:'تصغير',
    lifecycleAria:'مراحل توضيحية لاستعادة الإيرادات؛ لم يتم التحقق من أي مرحلة أو تنفيذها',lifecycleTitle:'دورة استعادة الإيرادات · توضيحية فقط',lifeSignal:'إشارة',lifeVerify:'تحقق',lifeAnalyze:'تحليل',lifeRank:'ترتيب',lifeDecide:'قرار',lifeExecute:'تنفيذ',lifeDemo:'تجريبي',lifeHypothesis:'فرضية',lifePending:'معلّق',lifeDisabled:'معطّل',
    dossierSignalLocation:'الإشارة والموقع',revenueLeakagePotential:'احتمال تسرب الإيرادات',hypotheticalRecoveryWorkflow:'سير عمل افتراضي للاستعادة',hypotheticalRecoveryText:'تصور فقط: قد يحدد سير عمل مستقبلي ومصرح به استفسارًا مؤهلًا لم تتم متابعته، ثم يوجهه للتحقق ويعد مسودة داخلية لموافقة شخص. لا توجد أي أنظمة متصلة هنا، ولا يُرسل شيء أو يُنفذ.',blueprintDetect:'اكتشاف استفسار محتمل فائت والتحقق منه بسجلات مصرّح بها.',blueprintRecover:'إعداد مسودة استعادة لقرار بشري؛ لا يتم إرسال أي شيء.',blueprintMeasure:'قياس حجز مؤكد ونتيجته اللاحقة فقط.',
    claimStates:'حالات الادعاء',claimLegendTitle:'قاموس حالات الأدلة',claimLegendHint:'تصف هذه التسميات حالات محتملة لادعاءات مستقبلية، وليست أدلة في هذا العرض. بيانات المثال الحالية فرضيات أو غير متحقق منها.',claimFact:'حقيقة',claimVerified:'متحقق منها',claimLikely:'مرجّح',claimHypothesis:'فرضية',claimUnverified:'غير متحقق منه',claimConflicting:'متعارض'
  },
  ru:{
    subtitle:'КОНЦЕПЦИЯ ВОЗВРАТА ДОХОДА ДЛЯ ДОМАШНИХ УСЛУГ · ТОЛЬКО ДЕМО',radarTitle:'Радар возврата дохода',radarSub:'Только синтетическая концепция процесса · нет актуальных данных LSA или клиентов, анализа ИИ, подтверждённых потерь или заявлений о возвращённой выручке.',mapTitle:'Радар возврата дохода',mapSub:'Реальная общедоступная география · вымышленные городские точки, не адреса компаний',
    globeView:'3D-глобус',map2dView:'2D-карта',visualModeAria:'Выбрать 3D-глобус или 2D-карту',globeAria:'Интерактивный 3D-глобус с вымышленными городскими маркерами. Поворачивайте стрелками, масштабируйте клавишами плюс и минус.',globeControlsAria:'Управление 3D-глобусом',globeInstructions:'Перетаскивайте для вращения · колесо или щипок для масштаба · выберите маркер, чтобы просмотреть синтетическую гипотезу. Прокручивайте страницу вне глобуса.',globeStatusReady:'Локальный 3D-глобус · все возможности синтетические',globeStatusNoWebgl:'WebGL недоступен · активна 2D-карта',globeStatusSlow:'Низкая производительность · выполнен переход на 2D-карту',globeStatusReduced:'Для производительности снижены визуальные эффекты',globePause:'Приостановить вращение',globeResume:'Возобновить вращение',globeZoomIn:'Приблизить',globeZoomOut:'Отдалить',
    lifecycleAria:'Иллюстративный цикл возврата дохода; этапы не проверены и не выполнены',lifecycleTitle:'ЦИКЛ ВОЗВРАТА ДОХОДА · ТОЛЬКО ИЛЛЮСТРАЦИЯ',lifeSignal:'СИГНАЛ',lifeVerify:'ПРОВЕРКА',lifeAnalyze:'АНАЛИЗ',lifeRank:'РАНЖИРОВАНИЕ',lifeDecide:'РЕШЕНИЕ',lifeExecute:'ВЫПОЛНЕНИЕ',lifeDemo:'ДЕМО',lifeHypothesis:'ГИПОТЕЗА',lifePending:'ОЖИДАЕТ',lifeDisabled:'ОТКЛЮЧЕНО',
    dossierSignalLocation:'СИГНАЛ И МЕСТОПОЛОЖЕНИЕ',revenueLeakagePotential:'Возможная утечка дохода',hypotheticalRecoveryWorkflow:'ГИПОТЕТИЧЕСКИЙ ПРОЦЕСС ВОЗВРАТА',hypotheticalRecoveryText:'Только концепция: в будущем авторизованный процесс мог бы отметить оставленный без ответа квалифицированный запрос, направить его на проверку и подготовить внутренний черновик для одобрения человеком. Здесь ничего не подключено, не отправляется и не выполняется.',blueprintDetect:'Обнаружить возможный пропущенный запрос и проверить его по разрешённым записям.',blueprintRecover:'Подготовить черновик для решения человека; ничего не отправлять.',blueprintMeasure:'Измерять только подтверждённую запись и её последующий результат.',
    claimStates:'СТАТУСЫ УТВЕРЖДЕНИЙ',claimLegendTitle:'Словарь статусов доказательств',claimLegendHint:'Метки описывают возможные статусы будущих утверждений, а не доказательства в демо. Текущие примеры — ГИПОТЕЗЫ или НЕ ПРОВЕРЕНЫ.',claimFact:'ФАКТ',claimVerified:'ПРОВЕРЕНО',claimLikely:'ВЕРОЯТНО',claimHypothesis:'ГИПОТЕЗА',claimUnverified:'НЕ ПРОВЕРЕНО',claimConflicting:'ПРОТИВОРЕЧИВО'
  },
  zh:{
    subtitle:'家庭服务收入追回概念 · 仅供演示',radarTitle:'收入追回雷达',radarSub:'仅为合成工作流概念 · 不接入实时 LSA 或客户数据、AI 分析、已验证损失或已追回收入。',mapTitle:'收入追回雷达',mapSub:'真实公开地理信息 · 虚构城市锚点，并非企业位置',
    globeView:'3D 地球',map2dView:'2D 地图',visualModeAria:'选择 3D 地球或 2D 地图',globeAria:'带有虚构城市标记的交互式 3D 地球。使用方向键旋转，使用加号和减号缩放。',globeControlsAria:'3D 地球控制',globeInstructions:'拖动以旋转 · 滚轮或双指捏合以缩放 · 选择标记查看合成假设。请在地球区域之外滚动页面。',globeStatusReady:'本地 3D 地球 · 所有机会均为合成示例',globeStatusNoWebgl:'WebGL 不可用 · 已启用 2D 地图',globeStatusSlow:'渲染性能较低 · 已切换回 2D 地图',globeStatusReduced:'已降低视觉效果以改善性能',globePause:'暂停旋转',globeResume:'恢复旋转',globeZoomIn:'放大',globeZoomOut:'缩小',
    lifecycleAria:'收入追回流程示意；没有任何阶段经过验证或执行',lifecycleTitle:'收入追回流程 · 仅为示意',lifeSignal:'信号',lifeVerify:'核验',lifeAnalyze:'分析',lifeRank:'排序',lifeDecide:'决策',lifeExecute:'执行',lifeDemo:'演示',lifeHypothesis:'假设',lifePending:'待定',lifeDisabled:'已禁用',
    dossierSignalLocation:'信号与位置',revenueLeakagePotential:'潜在收入流失',hypotheticalRecoveryWorkflow:'假设的追回工作流',hypotheticalRecoveryText:'仅为概念：未来经授权的工作流可能标记未获跟进的合格咨询，将其转交核验，并准备供人工批准的内部草稿。此处未连接任何系统，不会发送或执行任何操作。',blueprintDetect:'发现潜在漏接咨询，并用获准记录核验。',blueprintRecover:'准备供人工决策的追回草稿；不发送任何消息。',blueprintMeasure:'仅衡量已确认的预约及其后续结果。',
    claimStates:'主张状态',claimLegendTitle:'证据状态词汇',claimLegendHint:'这些标签描述未来主张可能采用的状态，并非本演示中的证据。当前示例仅为假设或未经核验。',claimFact:'事实',claimVerified:'已核验',claimLikely:'很可能',claimHypothesis:'假设',claimUnverified:'未经核验',claimConflicting:'存在冲突'
  },
  ko:{
    subtitle:'홈 서비스 매출 회수 콘셉트 · 데모 전용',radarTitle:'매출 회수 레이더',radarSub:'합성 워크플로 콘셉트만 제공 · 실시간 LSA·고객 데이터, AI 분석, 검증된 손실 또는 회수 매출 주장은 없습니다.',mapTitle:'매출 회수 레이더',mapSub:'실제 공개 지리 정보 · 가상의 도시 기준점이며 사업체 위치가 아닙니다',
    globeView:'3D 지구본',map2dView:'2D 지도',visualModeAria:'3D 지구본 또는 2D 지도 선택',globeAria:'가상의 도시 표식이 있는 대화형 3D 지구본입니다. 화살표 키로 회전하고 더하기와 빼기로 확대·축소하세요.',globeControlsAria:'3D 지구본 컨트롤',globeInstructions:'드래그하여 회전 · 휠 또는 핀치로 확대·축소 · 표식을 선택해 합성 가설을 확인하세요. 지구본 바깥에서 페이지를 스크롤하세요.',globeStatusReady:'로컬 3D 지구본 · 모든 기회는 합성 예시',globeStatusNoWebgl:'WebGL을 사용할 수 없음 · 2D 지도 활성화',globeStatusSlow:'렌더링 성능 저하 · 2D 지도로 전환됨',globeStatusReduced:'성능을 위해 시각 효과를 줄였습니다',globePause:'회전 일시 정지',globeResume:'회전 재개',globeZoomIn:'확대',globeZoomOut:'축소',
    lifecycleAria:'매출 회수 과정 예시이며 어떤 단계도 검증되거나 실행되지 않았습니다',lifecycleTitle:'매출 회수 과정 · 예시 전용',lifeSignal:'신호',lifeVerify:'검증',lifeAnalyze:'분석',lifeRank:'순위',lifeDecide:'결정',lifeExecute:'실행',lifeDemo:'데모',lifeHypothesis:'가설',lifePending:'대기',lifeDisabled:'비활성',
    dossierSignalLocation:'신호 및 위치',revenueLeakagePotential:'잠재적 매출 누수',hypotheticalRecoveryWorkflow:'가상 회수 워크플로',hypotheticalRecoveryText:'개념 설명만 제공합니다. 향후 승인된 워크플로라면 응답되지 않은 적격 문의를 표시하고 검증 절차로 전달한 뒤 사람이 승인할 내부 초안을 준비할 수 있습니다. 여기서는 어떤 시스템도 연결되지 않았으며 메시지를 보내거나 작업을 실행하지 않습니다.',blueprintDetect:'잠재적 미응답 문의를 탐지하고 승인된 기록으로 검증합니다.',blueprintRecover:'사람의 결정을 위한 회수 초안을 준비합니다. 메시지는 보내지 않습니다.',blueprintMeasure:'확인된 예약과 이후 결과만 측정합니다.',
    claimStates:'주장 상태',claimLegendTitle:'증거 상태 용어',claimLegendHint:'이 레이블은 향후 주장의 가능한 상태를 설명하며 이 데모의 증거가 아닙니다. 현재 예시는 가설 또는 미검증 상태뿐입니다.',claimFact:'사실',claimVerified:'검증됨',claimLikely:'가능성 높음',claimHypothesis:'가설',claimUnverified:'미검증',claimConflicting:'상충'
  }
};

Object.assign(phase5Translations.en,{syntheticIntelligence:'DEMO / SYNTHETIC INTELLIGENCE',hypotheticalRecoveryWorkflow:'HYPOTHETICAL AI SOLUTION · NOT CONNECTED'});
Object.assign(phase5Translations.fr,{syntheticIntelligence:'RENSEIGNEMENTS DE DÉMO / SYNTHÉTIQUES',hypotheticalRecoveryWorkflow:'SOLUTION IA HYPOTHÉTIQUE · NON CONNECTÉE'});
Object.assign(phase5Translations.ar,{syntheticIntelligence:'معلومات استخباراتية تجريبية / اصطناعية',hypotheticalRecoveryWorkflow:'حل ذكاء اصطناعي افتراضي · غير متصل'});
Object.assign(phase5Translations.ru,{syntheticIntelligence:'ДЕМО / СИНТЕТИЧЕСКИЕ ДАННЫЕ РАДАРА',hypotheticalRecoveryWorkflow:'ГИПОТЕТИЧЕСКОЕ РЕШЕНИЕ ИИ · НЕ ПОДКЛЮЧЕНО'});
Object.assign(phase5Translations.zh,{syntheticIntelligence:'演示 / 合成情报',hypotheticalRecoveryWorkflow:'假设的 AI 方案 · 未连接'});
Object.assign(phase5Translations.ko,{syntheticIntelligence:'데모 / 합성 인텔리전스',hypotheticalRecoveryWorkflow:'가상 AI 솔루션 · 미연결'});
Object.assign(phase5Translations.en,{map2dView:'2D Tactical Map'});
Object.assign(phase5Translations.fr,{map2dView:'Carte tactique 2D'});
Object.assign(phase5Translations.ar,{map2dView:'خريطة تكتيكية ثنائية الأبعاد'});
Object.assign(phase5Translations.ru,{map2dView:'Тактическая карта 2D'});
Object.assign(phase5Translations.zh,{map2dView:'2D 战术地图'});
Object.assign(phase5Translations.ko,{map2dView:'2D 전술 지도'});
Object.assign(phase5Translations.en,{coverageGlobal:'13 fictional city anchors across seven world regions, including Middle East'});
Object.assign(phase5Translations.fr,{coverageGlobal:'13 points de ville fictifs dans sept régions du monde, dont le Moyen-Orient'});
Object.assign(phase5Translations.ar,{coverageGlobal:'13 مرساة مدينية خيالية موزعة على سبع مناطق عالمية، منها الشرق الأوسط'});
Object.assign(phase5Translations.ru,{coverageGlobal:'13 вымышленных городских точек в семи регионах мира, включая Ближний Восток'});
Object.assign(phase5Translations.zh,{coverageGlobal:'13个虚构城市锚点，覆盖七个世界区域，包括中东'});
Object.assign(phase5Translations.ko,{coverageGlobal:'중동을 포함한 7개 세계 지역의 가상 도시 앵커 13개'});
